version: '3'
services:
  web:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=jedis_test_development
    volumes:
      - .:/app
  db:
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=jedis_test_development
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
